kind: pipeline
type: docker
name: default

steps:
# - name: build
#   image: docker
#   commands:
#     - docker build . -t drone-test:
#   volumes:
#     - name: dockersock
#       path: /var/run/docker.sock

- name: docker  
  image: plugins/docker
  settings:
    repo: drone-test
    tags: ${DRONE_BUILD_NUMBER}

# volumes:
#   - name: dockersock
#     host:
#       path: /var/run/docker.sock    

trigger:
  branch:
  - master
