kind: pipeline
type: docker
name: default

steps:
- name: build
  image: docker
  commands:
  - docker build . -t drone-test:${DRONE_BUILD_NUMBER}
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    
trigger:
  branch:
  - master
