workspace:
  base: /node
  path: drone/node-example

clone:
  git:
    image: plugins/git
    depath: 50
    tags: true

pipeline:
  frontend:
    image: node:8.3.0
    group: testing
    environment:
      - TOKEN=12345678
    secrets: 
      - source: TOKEN1
        target: TOKEN2
    commands:
      - yarn install
      - echo $TOKEN2
      - echo $TOKEN3
    when:
      branch: master
      
  backend:
    image: node:8.3.0
    group: testing
    environment:
      - TOKEN=12345678
    secrets: 
      - source: TOKEN1
        target: TOKEN3
    commands:
      - yarn install
      - echo $TOKEN2
      - echo $TOKEN3
    when:
      branch: develop
  
  curl:
    image: mrpolo17/drone_curl_plugin
    url: http://foo.com
    method: post
    body: |
      hello world
